---
apiVersion: v1
offerings:
  - name: terraform-ibm-icd-redis
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 63d401dc-e046-4f4b-916e-0c5af4888d81
    examples:
      - name: basic
        mark_ready: true
      - name: advanced
        mark_ready: true
      - name: fscloud
        mark_ready: true
